/**
 * `POST /documents/:id/share/link` — creates or revokes a tokenised link.
 *
 * The token is generated by the database (24 random bytes, hex) and never leaves
 * the owner's session: `share_links` is readable only by an owner/admin, so the
 * list on the page is the one place the token is ever shown.
 *
 * Revocation is a delete. An expired link is *not* deleted, so the page can still
 * show when it lapsed instead of pretending it never existed.
 */

import type { APIRoute } from 'astro';

import { isDocumentId, isUuid } from '@/lib/documents/ids';
import { sharePageUrl } from '@/lib/documents/messages';
import { createShareLink, revokeShareLink } from '@/lib/documents/repository';
import { expiryDate, isInviteRole, MAX_LINK_EXPIRY_DAYS } from '@/lib/documents/sharing';

export const POST: APIRoute = async (context) => {
  const { user, supabase } = context.locals;
  const documentId = context.params.id ?? '';

  if (!user || !supabase) return context.redirect('/login?next=/dashboard');
  if (!isDocumentId(documentId)) return context.redirect('/dashboard?error=not_found');

  const form = await context.request.formData();
  const action = String(form.get('action') ?? '');

  if (action === 'revoke') {
    const linkId = String(form.get('link') ?? '');
    if (!isUuid(linkId)) {
      return context.redirect(sharePageUrl(documentId, { error: 'link_failed' }), 303);
    }

    const result = await revokeShareLink(supabase, linkId);
    return context.redirect(
      sharePageUrl(documentId, result.ok ? { linkRevoked: true } : { error: 'link_failed' }),
      303,
    );
  }

  const role = form.get('role');
  if (action !== 'create' || !isInviteRole(role)) {
    return context.redirect(sharePageUrl(documentId, { error: 'link_failed' }), 303);
  }

  const requested = Number.parseInt(String(form.get('expiry') ?? '0'), 10);
  const days = Number.isFinite(requested)
    ? Math.min(Math.max(requested, 0), MAX_LINK_EXPIRY_DAYS)
    : 0;

  const result = await createShareLink(supabase, user.id, {
    documentId,
    role,
    expiresAt: expiryDate(days),
  });

  return context.redirect(
    sharePageUrl(
      documentId,
      result.ok
        ? { linkCreated: true }
        : { error: result.reason === 'forbidden' ? 'forbidden' : 'link_failed' },
    ),
    303,
  );
};
