export const ICONIFY_ICONS = {
  lucide: [
    'arrow-left',
    'arrow-up-down',
    'bold',
    'braces',
    'case-sensitive',
    'check',
    'chevron-down',
    'chevron-up',
    'circle-x',
    'clock',
    'code',
    'code-xml',
    'copy',
    'download',
    'ellipsis',
    'ellipsis-vertical',
    'eraser',
    'external-link',
    'eye',
    'eye-off',
    'file-code',
    'file-down',
    'file-plus',
    'file-text',
    'heading',
    'history',
    'image',
    'italic',
    'key-round',
    'layout-dashboard',
    'link',
    'link-2-off',
    'list',
    'loader-circle',
    'list-checks',
    'list-ordered',
    'list-tree',
    'lock',
    'log-in',
    'log-out',
    'mail',
    'mail-check',
    'message-square',
    'message-circle',
    'minus',
    'panel-left-close',
    'pencil-line',
    'plus',
    'printer',
    'quote',
    'redo-2',
    'rotate-ccw',
    'replace-all',
    'search',
    'send',
    'settings',
    'shield-check',
    'sliders-horizontal',
    'strikethrough',
    'table',
    'trash',
    'triangle-alert',
    'type',
    'undo-2',
    'upload',
    'user-check',
    'user-minus',
    'user-plus',
    'users',
    'workflow',
    'x',
    'zoom-in',
    'terminal',
  ],
  'simple-icons': ['github', 'google'],
} as const;

type IconifyIcons = typeof ICONIFY_ICONS;

export type IconSet = keyof IconifyIcons;

export type IconName = {
  [Set in IconSet]: `${Set}:${IconifyIcons[Set][number]}`;
}[IconSet];
